Algoritmo "Procedimentos - Referencia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Pequeno algoritmo para Passagem por referecia
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 14/10/2020

Procedimento soma(var a,b:inteiro)
Inicio
a <- (a + 1)
b <- (b + 2)
FimProcedimento


Var
x, y: inteiro


Inicio

x <- 4
y <- 8

soma(x,y)
Escreva (x, y)

Fimalgoritmo