Algoritmo "Transferencia por valor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 14/10/2020


Procedimento valor(a,b:inteiro)
Inicio
var c:inteiro

c <- (a+b)
FimProcedimento


   Var
   x, y: inteiro


Inicio

   x <- 2
   y <- 5
   valor(x,y)

   Escreval ("SOMA: " , c )

Fimalgoritmo